### ISSUE TITLE
How to send commands via Arduino IDE

### ISSUE THREAD

**Issue by cillianderoiste** [Kurokesu/motorized_zoom_lens#2]
I haven't used an arduino device before, so I wonder if I'm doing something silly. Should the commands mentioned in the README (https://github.com/Kurokesu/motorized_zoom_lens#commands) be sent using the Serial Monitor? Should they be sent literally as e.g. [G0 X100 Y100] on one line, with square brackets? What should the baud rate and line ending be set to?
I see no output in the monitor at all and I've tried many variations on the commands but they appear to have no effect.

**Comment by Lukse** [comment]
Commands should be sent without brackets with new line. Default baud rate is 115200bps. And sure, you can use Arduino Serial Monitor.

**Comment by cillianderoiste** [comment]
That works perfectly, thank you!
